// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQVHcjsXYegHITYt_eaHNwiSe_xIVgmF4',
    appId: '1:962854703408:web:37ad108fed42c2a563b8f5',
    messagingSenderId: '962854703408',
    projectId: 'flutterchat-5c597',
    authDomain: 'flutterchat-5c597.firebaseapp.com',
    storageBucket: 'flutterchat-5c597.appspot.com',
    measurementId: 'G-6WTBT5XYVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI89rddpYaDXv86VwJWZD7Moc8C8SEumc',
    appId: '1:962854703408:android:8f9cb391f48a4fe763b8f5',
    messagingSenderId: '962854703408',
    projectId: 'flutterchat-5c597',
    storageBucket: 'flutterchat-5c597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj1HdNwUyAyqFzPHQZbwcSGYA7R5ju6QQ',
    appId: '1:962854703408:ios:15c3fc4d62a0359063b8f5',
    messagingSenderId: '962854703408',
    projectId: 'flutterchat-5c597',
    storageBucket: 'flutterchat-5c597.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj1HdNwUyAyqFzPHQZbwcSGYA7R5ju6QQ',
    appId: '1:962854703408:ios:07489438e1e4465963b8f5',
    messagingSenderId: '962854703408',
    projectId: 'flutterchat-5c597',
    storageBucket: 'flutterchat-5c597.appspot.com',
    iosBundleId: 'com.example.flutterChat.RunnerTests',
  );
}
